### ISSUE TITLE
scrolling on switching screens and disappearing navbar

### ISSUE THREAD

**Issue by oldner** [elementary/switchboard-plug-applications#118]
Hey

Firstly I m a big fan of you. You really are making good things. Although I admire this operating system, I now have some issues that make me queasy.

One of them is about when i m trying to switching application screens with alt+tab. When i switched the app and try to scroll, the page scrolling up or down more than my pressure. But it does that only a time. If i try to switch another app it happens again. I encountered with these apps until now: Visual Studio Code and Google Chrome. It is started to be annoying.

Other is when i try to click top menu (status bar) where it has applications, time etc. If I click for the first time for that session, it is being destroyed and than it is turning back. 

Hope i could explain. If you need details of my system, please tell me how i can share with you. Thanks.

**Comment by hanaral** [comment]
Hi,
The issue of Google Chrome and VSC aren't really in the contol of the elementary team, but if you can elaborate on how it is still I might be able to help.
As for the Wingpanel crashing, thats a bug that is known and will be addressed. It shouldn't impact the usage much since it automatically comes bac after a moment.
