### ISSUE TITLE
Add 'About Apps' tab with information about installed apps

### ISSUE THREAD

**Issue by hanaral** [elementary/switchboard-plug-applications#147]
## Problem

There is no 'about X' in elementary HIG apps, this is perfectly fine. However, you shouldn't be redirected to the AppCenter if you want to view concise and relevant information about the app in the context of whats installed on your device.

## Proposal

There is a difference between AppCenter descriptions + details and the details that someone might want to know about the actual 'thing' they installed.
The main area could have:
- How much space it takes up and how much it's documents take up
- The app's name and a link to it's AppCenter page
- It's developer and a link to their website
- Details on when it was installed and whether an update is available

## Prior Art

iOS kinda has this with iPhone's storage under Settings > General
|  | Example |
------------ | -------------
| iPhone storage panel | ![photo_2021-01-26_15-39-59](https://user-images.githubusercontent.com/58219504/105867257-cc556080-5fec-11eb-9f3c-b18a3813c6a5.jpg) |

**Comment by cassidyjames** [comment]
I still don't see why this shouldn't be in AppCenter. A more useful Installed tab would be welcome, and the only thing proposed that we are missing is how much space apps take up. But the test of that is already in AppCenter listings.

@elementary/ux thoughts?

**Comment by hanaral** [comment]
Sorry to hijack my own issue, but I do have a couple of related ideas - 
The AppCenter would make more sense, but the installed tab right now feels more like a bland list of updatables - above a sea of things half of which aren't apps.
I think that the current macOS AppStore is quite nice and has a sidebar for navigation, which feels much more at home on a desktop - something like that could be good for immediately showing where the Installed, update-able and Curated apps are.

**Comment by danrabbit** [comment]
This page in iOS doesn't show just the size of the app itself but also the size of the files contained in its sandbox. It's part of a disk usage utility whose purpose is to help free up space. So for that particular purpose, it does seem outside the scope of AppCenter.

I think there's room for some discussion about a way to manage a variety of settings from an app-first perspective, but this particular feature in iOS isn't actually that.

But I have brought up before that it would be worth doing some research about whether it might make more sense to manage things like notification or location settings from a combined app page instead of navigating to notifications then the app, for example.

**Comment by hanaral** [comment]
I think this hasn't really gotten any traction
